theme: minima  # Optional, for default styling

# Enable pretty permalinks (optional)
permalink: pretty

# Define custom collections
collections:
  mypages:
    output: true  # Ensure _mypages/ generates URLs

# Apply "default.html" layout to all pages
defaults:
  - scope:
      path: ""  # Applies to everything
    values:
      layout: "default"
