title: "CTF Writeups"
description: "A collection of CTF challenges and writeups."
baseurl: ""
url: "https://DeepWaterSecurity.github.io"  

theme: minima  

collections:
  mypages:
    output: true  

# Markdown Processing
markdown: kramdown
permalink: pretty  # Ensures URLs don’t have .html extensions
