title: "CTF Writeups"
description: "A collection of CTF challenges and writeups."
baseurl: ""
url: "https://DeepWaterSecurity.github.io"  

theme: minima  

collections:
  mypages:
    output: true  

defaults:
  - scope:
      path: ""  # Applies to all files in the site
    values:
      layout: "default"  # Uses _layouts/default.html

# Markdown Processing
markdown: kramdown
permalink: pretty  # Ensures URLs don’t have .html extensions
